package com.sonesh.finance.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.sonesh.finance.repository.ExpenseRepository;
import com.sonesh.finance.repository.IncomeRepository;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

@Service
public class ReportService {

    private final IncomeRepository incomeRepository;
    private final ExpenseRepository expenseRepository;

    public ReportService(IncomeRepository incomeRepository,
                         ExpenseRepository expenseRepository) {
        this.incomeRepository = incomeRepository;
        this.expenseRepository = expenseRepository;
    }

    public ByteArrayInputStream generateMonthlyReport(String email, int year, int month) {

        double income = incomeRepository.getMonthlyIncomeTotal(email, year, month);
        double expense = expenseRepository.getMonthlyExpenseTotal(email, year, month);
        double savings = income - expense;

        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font textFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

            // Title
            Paragraph title = new Paragraph("FinTrack - Monthly Financial Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph(" "));

            // User details
            document.add(new Paragraph("User: " + email, textFont));
            document.add(new Paragraph("Year: " + year + " | Month: " + month, textFont));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Financial Summary", headerFont));
            document.add(new Paragraph(" "));

            // Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);

            table.addCell("Total Income");
            table.addCell("Rs. " + String.format("%.2f", income));

            table.addCell("Total Expense");
            table.addCell("Rs. " + String.format("%.2f", expense));

            table.addCell("Savings");
            table.addCell("Rs. " + String.format("%.2f", savings));

            document.add(table);

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by FinTrack - Personal Finance Management System", textFont));

            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
}